package com.run.spring.model;

import java.math.BigDecimal;

public class GradeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_grade_info.ID
     *
     * @mbggenerated Sat Dec 03 16:48:38 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_grade_info.STUDENT_ID
     *
     * @mbggenerated Sat Dec 03 16:48:38 CST 2016
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_grade_info.SUBJECT_ID
     *
     * @mbggenerated Sat Dec 03 16:48:38 CST 2016
     */
    private Integer subjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_grade_info.GRADE
     *
     * @mbggenerated Sat Dec 03 16:48:38 CST 2016
     */
    private BigDecimal grade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_grade_info.ID
     *
     * @return the value of tb_grade_info.ID
     *
     * @mbggenerated Sat Dec 03 16:48:38 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_grade_info.ID
     *
     * @param id the value for tb_grade_info.ID
     *
     * @mbggenerated Sat Dec 03 16:48:38 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_grade_info.STUDENT_ID
     *
     * @return the value of tb_grade_info.STUDENT_ID
     *
     * @mbggenerated Sat Dec 03 16:48:38 CST 2016
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_grade_info.STUDENT_ID
     *
     * @param studentId the value for tb_grade_info.STUDENT_ID
     *
     * @mbggenerated Sat Dec 03 16:48:38 CST 2016
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_grade_info.SUBJECT_ID
     *
     * @return the value of tb_grade_info.SUBJECT_ID
     *
     * @mbggenerated Sat Dec 03 16:48:38 CST 2016
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_grade_info.SUBJECT_ID
     *
     * @param subjectId the value for tb_grade_info.SUBJECT_ID
     *
     * @mbggenerated Sat Dec 03 16:48:38 CST 2016
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_grade_info.GRADE
     *
     * @return the value of tb_grade_info.GRADE
     *
     * @mbggenerated Sat Dec 03 16:48:38 CST 2016
     */
    public BigDecimal getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_grade_info.GRADE
     *
     * @param grade the value for tb_grade_info.GRADE
     *
     * @mbggenerated Sat Dec 03 16:48:38 CST 2016
     */
    public void setGrade(BigDecimal grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_grade_info
     *
     * @mbggenerated Sat Dec 03 16:48:38 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", studentId=").append(studentId);
        sb.append(", subjectId=").append(subjectId);
        sb.append(", grade=").append(grade);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_grade_info
     *
     * @mbggenerated Sat Dec 03 16:48:38 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GradeInfo other = (GradeInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getStudentId() == null ? other.getStudentId() == null : this.getStudentId().equals(other.getStudentId()))
            && (this.getSubjectId() == null ? other.getSubjectId() == null : this.getSubjectId().equals(other.getSubjectId()))
            && (this.getGrade() == null ? other.getGrade() == null : this.getGrade().equals(other.getGrade()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_grade_info
     *
     * @mbggenerated Sat Dec 03 16:48:38 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getStudentId() == null) ? 0 : getStudentId().hashCode());
        result = prime * result + ((getSubjectId() == null) ? 0 : getSubjectId().hashCode());
        result = prime * result + ((getGrade() == null) ? 0 : getGrade().hashCode());
        return result;
    }
}