package com.run.spring.model;

public class TestChild {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test_chind.ID
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test_chind.VLAUE
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    private String vlaue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test_chind.ID
     *
     * @return the value of tb_test_chind.ID
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test_chind.ID
     *
     * @param id the value for tb_test_chind.ID
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test_chind.VLAUE
     *
     * @return the value of tb_test_chind.VLAUE
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    public String getVlaue() {
        return vlaue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test_chind.VLAUE
     *
     * @param vlaue the value for tb_test_chind.VLAUE
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    public void setVlaue(String vlaue) {
        this.vlaue = vlaue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_chind
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", vlaue=").append(vlaue);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_chind
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TestChild other = (TestChild) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getVlaue() == null ? other.getVlaue() == null : this.getVlaue().equals(other.getVlaue()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_chind
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getVlaue() == null) ? 0 : getVlaue().hashCode());
        return result;
    }
}