package com.run.spring.dao;

import com.run.spring.model.GradeInfo;
import com.run.spring.model.GradeInfoExample;
import java.util.List;

public interface GradeInfoDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_grade_info
     *
     * @mbggenerated Sat Dec 03 16:48:38 CST 2016
     */
    int countByExample(GradeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_grade_info
     *
     * @mbggenerated Sat Dec 03 16:48:38 CST 2016
     */
    int deleteByExample(GradeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_grade_info
     *
     * @mbggenerated Sat Dec 03 16:48:38 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_grade_info
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    Integer insert(GradeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_grade_info
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    Integer insertSelective(GradeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_grade_info
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    List<GradeInfo> selectByExample(GradeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_grade_info
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    GradeInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_grade_info
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    int updateByExampleSelective(GradeInfo record, GradeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_grade_info
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    int updateByExample(GradeInfo record, GradeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_grade_info
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    int updateByPrimaryKeySelective(GradeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_grade_info
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    int updateByPrimaryKey(GradeInfo record);
}