package com.run.spring.dao;

import com.run.spring.model.TestChild;
import com.run.spring.model.TestChildExample;
import java.util.List;

public interface TestChildDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_chind
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    int countByExample(TestChildExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_chind
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    int deleteByExample(TestChildExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_chind
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_chind
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    Integer insert(TestChild record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_chind
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    Integer insertSelective(TestChild record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_chind
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    List<TestChild> selectByExample(TestChildExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_chind
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    TestChild selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_chind
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    int updateByExampleSelective(TestChild record, TestChildExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_chind
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    int updateByExample(TestChild record, TestChildExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_chind
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    int updateByPrimaryKeySelective(TestChild record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_chind
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    int updateByPrimaryKey(TestChild record);
}