package com.run.spring.dao;

import com.run.spring.model.TestChild;
import com.run.spring.model.TestChildExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TestChildDAOImpl extends SqlMapClientDaoSupport implements TestChildDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_chind
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    public TestChildDAOImpl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_chind
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    public int countByExample(TestChildExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tb_test_chind.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_chind
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    public int deleteByExample(TestChildExample example) {
        int rows = getSqlMapClientTemplate().delete("tb_test_chind.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_chind
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    public int deleteByPrimaryKey(Integer id) {
        TestChild _key = new TestChild();
        _key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tb_test_chind.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_chind
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    public Integer insert(TestChild record) {
        Object newKey = getSqlMapClientTemplate().insert("tb_test_chind.insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_chind
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    public Integer insertSelective(TestChild record) {
        Object newKey = getSqlMapClientTemplate().insert("tb_test_chind.insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_chind
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    @SuppressWarnings("unchecked")
    public List<TestChild> selectByExample(TestChildExample example) {
        List<TestChild> list = getSqlMapClientTemplate().queryForList("tb_test_chind.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_chind
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    public TestChild selectByPrimaryKey(Integer id) {
        TestChild _key = new TestChild();
        _key.setId(id);
        TestChild record = (TestChild) getSqlMapClientTemplate().queryForObject("tb_test_chind.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_chind
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    public int updateByExampleSelective(TestChild record, TestChildExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_test_chind.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_chind
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    public int updateByExample(TestChild record, TestChildExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_test_chind.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_chind
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    public int updateByPrimaryKeySelective(TestChild record) {
        int rows = getSqlMapClientTemplate().update("tb_test_chind.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_test_chind
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    public int updateByPrimaryKey(TestChild record) {
        int rows = getSqlMapClientTemplate().update("tb_test_chind.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_test_chind
     *
     * @mbggenerated Sat Dec 03 16:48:39 CST 2016
     */
    protected static class UpdateByExampleParms extends TestChildExample {
        private Object record;

        public UpdateByExampleParms(Object record, TestChildExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}